CREATE DATABASE CB;

CREATE TABLE CONTA_BANCARIA (
CODIGO 	INT		PRIMARY KEY, 		-- Código interno (PK)
TITULAR VARCHAR(32) 	NOT NULL,		-- Nome do titular da conta
SALDO   REAl      	NOT NULL		-- Representa o saldo da conta
);

INSERT INTO CONTA_BANCARIA VALUES (1, 'André', 213);
INSERT INTO CONTA_BANCARIA VALUES (2, 'Diogo', 489);
INSERT INTO CONTA_BANCARIA VALUES (3, 'Rafael', 568);
INSERT INTO CONTA_BANCARIA VALUES (4, 'Carlos', 712);
INSERT INTO CONTA_BANCARIA VALUES (5, 'Peter', -38);

START TRANSACTION;
UPDATE CONTA_BANCARIA SET SALDO = SALDO + (SALDO / 100 * 3)
WHERE SALDO > 0;
COMMIT;